### ISSUE TITLE
Make ghcr docker image reference lowercase

### ISSUE THREAD

**Issue by envest** [AlexsLemonade/medulloblastoma-classifier#71]
I'm working on this project locally (but same applied to remote instance) and had some issues getting the docker image to work on my Mac M1. There are helpful + clear directions for how to pull and run the docker container in the `README.md`.

When I use the `docker pull` command as given in the directions:

`docker pull ghcr.io/AlexsLemonade/medulloblastoma-classifier:latest`

I get this error:

`invalid reference format: repository name must be lowercase`

However, after changing the reference to lowercase, things work fine:

`docker pull ghcr.io/alexslemonade/medulloblastoma-classifier:latest`

especially after I add the tag `--platform linux/amd64` when running on my mac m1 laptop.

Same goes for the `docker run` command. I wanted to check with others to see if this matches the general user experience before committing to changes in a PR. Thanks!

**Comment by envest** [comment]
Image names must be lowercase! But some workflows handle it beneath the surface...

https://github.com/orgs/community/discussions/27086

**Comment by jashapiro** [comment]
That sounds right to me!
