### ISSUE TITLE
Additional 10X 3' scRNA data

### ISSUE THREAD

**Issue by envest** [AlexsLemonade/medulloblastoma-classifier#74]
The single cell data we currently have (https://www.nature.com/articles/s41586-019-1434-6) was generated using Smart-seq2, which is less sparse than 10X 3' scRNA-seq. What if we found an additional data set to test on? If we're going to make claims about single cell data, it would be nice for the claims to be explored using the most prevalent (I assume) type of single cell data.

**Comment by jaclyn-taroni** [comment]
Maybe:

- https://pmc.ncbi.nlm.nih.gov/articles/PMC8804892/
- https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE155446
